import { CommonModule } from '@angular/common';
import { Component, Inject } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { MAT_DIALOG_DATA, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { ApiDataService } from '../../../../core/http/api.service';
import { ApiRoutesConstants } from '../../../../shared/common-services/api-route-constants';
import { ToastService } from '../../../../shared/common-services/toast.service';

@Component({
  selector: 'app-add-organization-form',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, MatDialogModule],
  templateUrl: './add-organization-form.html',
  styleUrl: './add-organization-form.scss',
})
export class AddOrganizationForm {
  orgForm: FormGroup;
  isSaving = false;
  /** Auto-generated by the backend (e.g. RP-0001) - never entered by hand, only shown once
   *  it exists (i.e. when editing something the server already assigned a code to). */
  readonly code: string | null;

  readonly typeOptions = [
    { value: 'branch', label: 'Branch' },
    { value: 'franchise', label: 'Franchise' },
  ];

  constructor(
    private fb: FormBuilder,
    private dialogRef: MatDialogRef<AddOrganizationForm>,
    private apiDataService: ApiDataService,
    private toast: ToastService,
    @Inject(MAT_DIALOG_DATA) public data: any
  ) {
    this.code = data?.code ?? null;

    this.orgForm = this.fb.group({
      type: [data?.type ?? 'branch', Validators.required],
      name: [data?.name ?? '', [Validators.required, Validators.maxLength(150)]],
      address: [data?.address ?? ''],
      pincode: [data?.pincode ?? '', [Validators.maxLength(10)]],
      phone_no: [data?.phone_no ?? '', [Validators.pattern(/^[0-9]{10,15}$/)]],
      email: [data?.email ?? '', [Validators.email, Validators.maxLength(150)]],
      gst_number: [data?.gst_number ?? '', [Validators.maxLength(15)]],
      description: [data?.description ?? ''],
      status: [this.resolveStatus(data?.status), Validators.required],
    });
  }

  get isEdit(): boolean {
    return !!this.data?.id;
  }

  /** status is the raw 1/0 tinyint from Postgres - defensive against a string "active"/"inactive"
   *  too, in case that ever changes upstream. */
  private resolveStatus(status: unknown): number {
    if (typeof status === 'string') {
      return status.trim().toLowerCase() === 'active' || status === '1' ? 1 : 0;
    }
    return status === 0 ? 0 : 1;
  }

  saveOrganization(): void {
    if (this.orgForm.invalid) {
      this.orgForm.markAllAsTouched();
      return;
    }

    const raw = this.orgForm.getRawValue();
    const payload = {
      type: raw.type,
      name: raw.name.trim(),
      address: raw.address?.trim() || null,
      pincode: raw.pincode?.trim() || null,
      phone_no: raw.phone_no?.trim() || null,
      email: raw.email?.trim() || null,
      gst_number: raw.gst_number ? raw.gst_number.trim().toUpperCase() : null,
      description: raw.description?.trim() || null,
      // The backend validates status as a string ("sometimes|string|max:30") even though the
      // column is a tinyint - Postgres happily casts a numeric string, but a JSON number fails
      // Laravel's `string` rule outright, so this must go as '1'/'0', not 1/0.
      status: String(raw.status),
    };

    this.isSaving = true;

    const request = this.isEdit
      ? this.apiDataService.PUT(`${ApiRoutesConstants.ORGANIZATION_ADD}/${this.data.id}`, payload)
      : this.apiDataService.POST(ApiRoutesConstants.ORGANIZATION_ADD, payload);

    request.subscribe({
      next: (response: any) => {
        this.isSaving = false;

        if (response && response.success !== false) {
          this.toast.success(this.isEdit ? 'Organization unit updated successfully' : 'Organization unit created successfully');
          this.dialogRef.close(response.data ?? payload);
        } else {
          this.toast.error(response?.message || 'Failed to save organization unit. Please try again.');
        }
      },
      error: (err: any) => {
        this.isSaving = false;
        const errors = err?.error?.errors;
        const firstError = errors ? (Object.values(errors)[0] as string[])?.[0] : null;
        this.toast.error(firstError || err?.error?.message || 'Failed to save organization unit. Please try again.');
        console.error('Failed to save organization unit:', err);
      },
    });
  }

  close(): void {
    this.dialogRef.close();
  }

  isInvalid(controlName: string): boolean {
    const control = this.orgForm.get(controlName);
    return !!(control && control.invalid && (control.dirty || control.touched));
  }
}
