import { ReportTab } from './reports.model';

export const REPORTS: ReportTab[] = [
  {
    id: 'lead-source',
    label: 'Lead Source',
    category: 'Lead Management',
    icon: 'bi-signpost-2-fill',
    variant: 'blue',
    description: 'Breakdown of leads by the channel they came in from - referral, website, walk-in and more.',
  },
  {
    id: 'lead-conversion',
    label: 'Lead Conversion',
    category: 'Lead Management',
    icon: 'bi-graph-up-arrow',
    variant: 'green',
    description: 'How many leads move from new to won at each stage of the pipeline.',
  },
  {
    id: 'lead-status',
    label: 'Lead Status',
    category: 'Lead Management',
    icon: 'bi-flag-fill',
    variant: 'orange',
    description: 'Current distribution of leads across every status - new, contacted, qualified, lost and won.',
  },
  {
    id: 'follow-up',
    label: 'Follow-up',
    category: 'Lead Management',
    icon: 'bi-arrow-repeat',
    variant: 'purple',
    description: 'Follow-ups completed on time versus overdue, grouped by the assigned caller.',
  },
  {
    id: 'appointment',
    label: 'Appointment',
    category: 'Appointments',
    icon: 'bi-calendar2-check-fill',
    variant: 'primary',
    description: 'Appointments scheduled, completed and missed across every branch.',
  },
  {
    id: 'customer',
    label: 'Customer',
    category: 'Customer Management',
    icon: 'bi-person-lines-fill',
    variant: 'red',
    description: 'Customer growth, retention and service history at a glance.',
  },
  {
    id: 'team-performance',
    label: 'Team Performance',
    category: 'Roles & Team',
    icon: 'bi-people-fill',
    variant: 'gray',
    description: 'Leads handled, conversions closed and average response time per team member.',
  },
  {
    id: 'service-category',
    label: 'Service Category',
    category: 'Settings',
    icon: 'bi-tags-fill',
    variant: 'blue',
    description: 'Demand across every service category, ranked by leads and bookings.',
  },
  {
    id: 'revenue',
    label: 'Revenue',
    category: 'Customer Management',
    icon: 'bi-cash-stack',
    variant: 'green',
    description: 'Revenue booked from converted leads, broken down by month and branch.',
  },
  {
    id: 'monthly-summary',
    label: 'Monthly Summary',
    category: 'Overview',
    icon: 'bi-bar-chart-fill',
    variant: 'purple',
    description: 'A rollup of every key metric across leads, appointments and customers for the month.',
  },
];
